AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/*'
    - '*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
