language: ruby
rvm: 2.7.0
cache: bundler
services:
  - postgresql
git:
  quiet: true
branches:
  except:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_5a7e44ae5516_key -iv $encrypted_5a7e44ae5516_iv -in test.key.enc -out config/credentials/test.key -d
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec